language: node_js
node_js:
  - "14"
dist: focal # ubuntu 20.04
services:
  - postgresql
  - redis-server
addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
env:
  global:
    - PGUSER=postgres
    - PGPORT=5432 # for some reason unlike what documentation says, the port is 5432
  jobs:
    - NODE_ENV=ci
cache:
  directories:
    - node_modules
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - postgres --version
  - pg_lsclusters # shows port of postgresql, ubuntu specific command
install:
  - npm i
  - npm list --depth 0
before_script:
  - sudo psql -c 'create database orm_test;' -p 5432 -U postgres
script:
  - npm run test-detectopen