CREATE TABLE authors (
    id INT GENERATED ALWAYS AS IDENTITY,
    name TEXT NOT NULL,
    age INT
);

CREATE TABLE books (
    id INT GENERATED ALWAYS AS IDENTITY,
    name TEXT,
    genre VARCHAR(10),
    author_id INT
);CREATE TABLE authors (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT NOT NULL ,age INT  );CREATE TABLE books (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT  ,genre VARCHAR(10)  ,author_id INT  );CREATE TABLE authors (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT NOT NULL ,age INT  );CREATE TABLE books (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT  ,genre VARCHAR(10)  ,author_id INT  );CREATE TABLE authors (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT NOT NULL ,age INT  );CREATE TABLE books (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT  ,genre VARCHAR(10)  ,author_id INT  );CREATE TABLE authors (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT NOT NULL ,age INT  );CREATE TABLE books (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT  ,genre VARCHAR(10)  ,author_id INT  );CREATE TABLE authors (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT NOT NULL ,age INT  );CREATE TABLE books (id INT GENERATED ALWAYS AS IDENTITY  ,name TEXT  ,genre VARCHAR(10)  ,author_id INT  );